{% set name = "CaImAn" %}
{% set version = "1.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatironinstitute/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2182259ba50f42d4b686adc8f187afffcddba30cb61995a0a3213a176684888e

build:
  number: 0
  skip: true  # [py<37]

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - pip
    - numpy
    - cython
    - ripgrep
  run:
    - python
    - tensorflow
    - bokeh
    - future
    - h5py =2.10.0
    - holoviews
    - ipykernel
    - ipython
    - ipyparallel
    - jupyter
    - matplotlib
    - mypy
    - nose
    - numpy
    - opencv
    - pandas
    - peakutils
    - pims
    - psutil
    - pynwb =1.4.0
    - pyqtgraph
    - scipy
    - scikit-image
    - scikit-learn
    - tifffile
    - tk >=8,!=8.6.9
    - tqdm
test:
  imports:
    - caiman
  commands:
    - caimanmanager.py install
    - caimanmanager.py check
    - caimanmanager.py test

about:
  home: http://github.com/flatironinstitute/caiman
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Calcium imaging analysis - 1p, 2p microscopy

  description: |
    CaImAn implements a set of essential methods required in analysis
    pipelines for large scale calcium imaging data. It implements fast, scalable algorithms
    for motion correction, source extraction, spike deconvolution, and component
    registration across multiple days. It is suitable for both two-photon and one-photon
    fluorescence microscopy data, and can be run in both batch and online modes.
  doc_url: http://caiman.readthedocs.io
  dev_url: https://github.com/flatironinstitute/CaImAn

extra:
  recipe-maintainers:
    - pgunn
    - epnev
    - zbarry
    - agiovann
