{% set name = "CaImAn" %}
{% set version = "1.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatironinstitute/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f7d5e34a92c19891cbd09137c4a3315d9a2cbadc582ef6d1ccfc27219a7fb367

build:
  number: 0
  skip: True  # [py<36]

requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - pip
    - numpy
    - cython
    - ripgrep
  run:
    - python
    - tensorflow
    - bokeh
    - future
    - h5py
    - holoviews
    - ipykernel
    - ipython
    - ipyparallel
    - jupyter
    - matplotlib
    - mypy
    - nose
    - numpy
    - opencv
    - peakutils
    - pims
    - scipy
    - scikit-image
    - scikit-learn
    - spyder
    - tifffile=0.15.1
    - tk >=8,!=8.6.9
    - tqdm
    - pyqtgraph
    - pynwb

test:
  imports:
    - caiman
  commands:
    - caimanmanager.py install
    - caimanmanager.py check
    - caimanmanager.py test

about:
  home: http://github.com/flatironinstitute/caiman
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Calcium imaging analysis - 1p, 2p microscopy'

  description: |
    CaImAn implements a set of essential methods required in the analysis
    pipeline of large scale calcium imaging data. Fast and scalable algorithms
    are implemented for motion correction, source extraction, spike
    deconvolution, and component registration across multiple days. It is
    suitable for both two-photon and one-photon fluorescence microscopy data,
    and can be run in both batch and online mode.
  doc_url: http://caiman.readthedocs.io
  dev_url: https://github.com/flatironinstitute/CaImAn

extra:
  recipe-maintainers:
    - pgunn
    - epnev
    - zbarry
    - agiovann
