{% set name = "CaImAn" %}
{% set version = "1.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatironinstitute/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a2bb5a11fd4e8dcd293730d780cd6187b07956cd0e840c27041ea9e7c7ac75e8

build:
  number: 0
  skip: true  # [py<39]
  entry_points:
    - caimanmanager = caiman.caimanmanager:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy <2.0.0                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - ripgrep
  host:
    - python
    - pip
    - setuptools
    - numpy <2.0.0
    - cython
  run:
    - python
    - av
    - bokeh >=3.1.1
    - h5py >=2.10.0
    - holoviews >=1.16.2
    - ipykernel
    - ipython
    - ipyparallel
    - jinja2 >=3.1.1
    - jupyter
    - jupyter_bokeh
    - matplotlib
    - mypy
    - nose
    - numpy <2.0.0
    - opencv
    - pandas
    - panel >=1.0.2
    - peakutils >=1.3.5
    - pims
    - psutil
    - pynwb
    - pyqtgraph
    - scipy >=1.10.1
    - scikit-image >=0.19.0
    - scikit-learn >=1.2
    - tensorflow >=2.4.0,<2.16
    - tifffile
    - tk >=8,!=8.6.9
    - tqdm
    - zarr
test:
  imports:
    - caiman
  commands:
    - caimanmanager install
    - caimanmanager check
    - caimanmanager test

about:
  home: http://github.com/flatironinstitute/caiman
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Calcium imaging analysis - 1p, 2p microscopy

  description: |
    CaImAn implements a set of essential methods required in analysis
    pipelines for large scale calcium imaging data. It implements fast, scalable algorithms
    for motion correction, source extraction, spike deconvolution, and component
    registration across multiple days. It is suitable for both two-photon and one-photon
    fluorescence microscopy data, and can be run in both batch and online modes.
  doc_url: http://caiman.readthedocs.io
  dev_url: https://github.com/flatironinstitute/CaImAn

extra:
  recipe-maintainers:
    - pgunn
