{% set name = "CaImAn" %}
{% set version = "1.9.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flatironinstitute/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a6ab15ff5349b9dedd9db96583911c440a7e3eb21008d51e9934b11558b3f285

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ripgrep
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - tensorflow >=2.4.0
    - bokeh
    - future
    - h5py >=2.10.0
    - holoviews =1.15.2
    - ipykernel
    - ipython
    - ipyparallel
    - jinja2 >=3.1.1
    - jupyter
    - matplotlib
    - mypy
    - nose
    - numpy
    - opencv
    - pandas
    - panel >=0.12.7
    - peakutils
    - pims
    - psutil
    - pynwb
    - pyqtgraph
    - scipy
    - scikit-image >=0.19.0
    - scikit-learn >=1.2
    - tifffile
    - tk >=8,!=8.6.9
    - tqdm
    - z5py >=2.0.15
test:
  imports:
    - caiman
  commands:
    - caimanmanager.py install
    - caimanmanager.py check
    - caimanmanager.py test

about:
  home: http://github.com/flatironinstitute/caiman
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Calcium imaging analysis - 1p, 2p microscopy

  description: |
    CaImAn implements a set of essential methods required in analysis
    pipelines for large scale calcium imaging data. It implements fast, scalable algorithms
    for motion correction, source extraction, spike deconvolution, and component
    registration across multiple days. It is suitable for both two-photon and one-photon
    fluorescence microscopy data, and can be run in both batch and online modes.
  doc_url: http://caiman.readthedocs.io
  dev_url: https://github.com/flatironinstitute/CaImAn

extra:
  recipe-maintainers:
    - pgunn
    - EricThomson
